import type { Provider, Type } from '@angular/core';
import type { StyleguidePage } from './page.types.js';

export interface NgPrismPlugin {
  /** Unique plugin name — used for debugging and conflict detection */
  name: string;

  // Build-time hooks (run inside the Angular builder / Node.js)
  onComponentScanned?: (component: ScannedComponent) => ScannedComponent | void | Promise<ScannedComponent | void>;
  onPageScanned?: (page: StyleguidePage) => StyleguidePage | void | Promise<StyleguidePage | void>;
  onManifestReady?: (manifest: PrismManifest) => PrismManifest | void | Promise<PrismManifest | void>;

  // Runtime contributions (embedded into the Prism app)
  panels?: PanelDefinition[];
  controls?: ControlDefinition[];
  /** Angular standalone component that wraps each rendered component */
  wrapComponent?: Type<unknown>;
}

export interface PanelDefinition {
  id: string;
  label: string;
  /** Angular standalone component for the panel content */
  component?: Type<unknown>;
  /** Lazy-loaded component — use when the component import would pull in browser-only dependencies (e.g. DomSanitizer) */
  loadComponent?: () => Promise<Type<unknown>>;
  overlayComponent?: Type<unknown>;
  loadOverlayComponent?: () => Promise<Type<unknown>>;
  icon?: string;
  position?: 'bottom' | 'right';
  /** Where this panel appears: 'addon' (bottom/right tabbar) or 'view' (top view toolbar). Default: 'addon' */
  placement?: 'addon' | 'view';
  /** Providers injected into a child EnvironmentInjector scoped to this panel */
  providers?: Provider[];
  /** When provided, the panel tab is only shown if this returns true for the active component */
  isVisible?: (component: RuntimeComponent) => boolean;
}

export interface ControlDefinition {
  /** Returns true if this control should handle the given input */
  matchType: (input: InputMeta) => boolean;
  /** Angular standalone component that renders the control */
  component: Type<unknown>;
}

// --- Manifest types (generated by the builder scanner) ---

export interface PrismManifest {
  components: ScannedComponent[];
  pages?: StyleguidePage[];
}

export interface ScannedComponent {
  className: string;
  filePath: string;
  showcaseConfig: import('../decorator/showcase.types.js').ShowcaseConfig;
  inputs: InputMeta[];
  outputs: OutputMeta[];
  componentMeta: {
    selector: string;
    standalone: boolean;
    isDirective: boolean;
  };
  /** Import path for the component's entry point (e.g. 'my-lib/atoms/pill') */
  importPath?: string;
  /** Arbitrary plugin metadata */
  meta?: Record<string, unknown>;
}

export interface InputMeta {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'union' | 'array' | 'object' | 'unknown';
  rawType?: string;
  values?: string[];
  defaultValue?: unknown;
  required: boolean;
  doc?: string;
}

export interface OutputMeta {
  name: string;
  doc?: string;
}

// --- Runtime manifest types (post-builder, contains actual class references) ---

export interface RuntimeManifest {
  components: RuntimeComponent[];
  pages?: StyleguidePage[];
}

export interface RuntimeComponent {
  meta: ScannedComponent;
  type: Type<unknown>;
}

// --- defineConfig types ---

export interface NgPrismConfig {
  plugins?: NgPrismPlugin[];
  pages?: StyleguidePage[];
  /** Providers added to the Prism app bootstrap — for library-wide services */
  appProviders?: Provider[];
  theme?: Record<string, string>;
  darkTheme?: Record<string, string>;
  lightTheme?: Record<string, string>;
  logo?: {
    light?: string;
    dark?: string;
  };
  title?: string;
  themeStylesheet?: string;
  ui?: {
    header?: Type<unknown>;
    sidebar?: Type<unknown>;
    componentHeader?: Type<unknown>;
    renderer?: Type<unknown>;
    controlsPanel?: Type<unknown>;
    eventsPanel?: Type<unknown>;
    footer?: Type<unknown>;
  };
  headless?: boolean;
  appComponent?: Type<unknown>;
  /** When false, disables URL state sync (default: true). */
  urlState?: boolean;
}
