import type { ScannedComponent } from '../../plugin/plugin.types.js';
import { generateManifest } from './manifest.generator.js';

const BUTTON: ScannedComponent = {
  className: 'ButtonComponent',
  filePath: 'src/lib/button/button.component.ts',
  showcaseConfig: {
    title: 'Button',
    category: 'Inputs',
    variants: [
      { name: 'Primary', inputs: { variant: 'primary', label: 'Click me' } },
      { name: 'Danger', inputs: { variant: 'danger', disabled: true } },
    ],
  },
  inputs: [
    { name: 'variant', type: 'union', values: ['primary', 'secondary', 'danger'], defaultValue: 'primary', required: false, doc: 'Visual appearance' },
    { name: 'label', type: 'string', defaultValue: 'Button', required: false },
    { name: 'disabled', type: 'boolean', defaultValue: false, required: false },
  ],
  outputs: [{ name: 'clicked', doc: 'Click event' }],
  componentMeta: { selector: 'my-button', standalone: true },
};

const CARD: ScannedComponent = {
  className: 'CardComponent',
  filePath: 'src/lib/card/card.component.ts',
  showcaseConfig: { title: 'Card', category: 'Layout' },
  inputs: [
    { name: 'title', type: 'string', defaultValue: '', required: false },
  ],
  outputs: [],
  componentMeta: { selector: 'my-card', standalone: true },
};

describe('generateManifest', () => {
  it('should generate valid TypeScript source', () => {
    const source = generateManifest([BUTTON, CARD]);

    expect(source).toContain('// AUTO-GENERATED by ng-prism');
    expect(source).toContain("import type { PrismManifest } from 'ng-prism/plugin'");
    expect(source).toContain('export const PRISM_MANIFEST: PrismManifest');
  });

  it('should include all components', () => {
    const source = generateManifest([BUTTON, CARD]);

    expect(source).toContain("className: \"ButtonComponent\"");
    expect(source).toContain("className: \"CardComponent\"");
  });

  it('should include showcase config', () => {
    const source = generateManifest([BUTTON]);

    expect(source).toContain('title: "Button"');
    expect(source).toContain('category: "Inputs"');
  });

  it('should include variants', () => {
    const source = generateManifest([BUTTON]);

    expect(source).toContain('name: "Primary"');
    expect(source).toContain('name: "Danger"');
  });

  it('should include inputs with type info', () => {
    const source = generateManifest([BUTTON]);

    expect(source).toContain('name: "variant"');
    expect(source).toContain('type: "union"');
    expect(source).toContain('values: [');
    expect(source).toContain('"primary"');
    expect(source).toContain('"secondary"');
    expect(source).toContain('"danger"');
  });

  it('should include outputs', () => {
    const source = generateManifest([BUTTON]);

    expect(source).toContain('name: "clicked"');
    expect(source).toContain('doc: "Click event"');
  });

  it('should include component meta', () => {
    const source = generateManifest([BUTTON]);

    expect(source).toContain('selector: "my-button"');
    expect(source).toContain('standalone: true');
  });

  it('should handle empty components array', () => {
    const source = generateManifest([]);

    expect(source).toContain('components: [');
    // No component entries between [ and ]
    expect(source).not.toContain('className:');
  });

  it('should handle components with empty outputs', () => {
    const source = generateManifest([CARD]);

    expect(source).toContain('outputs: []');
  });
});
