import type { ScannedComponent } from '../../plugin/plugin.types.js';

/**
 * Generate TypeScript source code for a prism-manifest.ts file.
 */
export function generateManifest(
  components: ScannedComponent[],
): string {
  const lines: string[] = [
    '// AUTO-GENERATED by ng-prism — do not edit!',
    "import type { PrismManifest } from 'ng-prism/plugin';",
    '',
    'export const PRISM_MANIFEST: PrismManifest = {',
    '  components: [',
  ];

  for (const comp of components) {
    lines.push('    {');
    lines.push(`      className: ${json(comp.className)},`);
    lines.push(`      filePath: ${json(comp.filePath)},`);
    lines.push(`      showcaseConfig: ${formatObject(comp.showcaseConfig as unknown as Record<string, unknown>, 6)},`);
    lines.push(`      inputs: ${formatArray(comp.inputs, 6)},`);
    lines.push(`      outputs: ${formatArray(comp.outputs, 6)},`);
    lines.push(`      componentMeta: ${formatObject(comp.componentMeta, 6)},`);
    lines.push('    },');
  }

  lines.push('  ],');
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

function json(value: unknown): string {
  return JSON.stringify(value);
}

function indent(depth: number): string {
  return ' '.repeat(depth);
}

function formatObject(obj: Record<string, unknown>, baseIndent: number): string {
  const entries = Object.entries(obj).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '{}';

  const inner = baseIndent + 2;
  const lines = entries.map(([key, value]) => {
    const formatted = Array.isArray(value)
      ? formatArray(value, inner)
      : typeof value === 'object' && value !== null
        ? formatObject(value as Record<string, unknown>, inner)
        : json(value);
    return `${indent(inner)}${key}: ${formatted},`;
  });

  return `{\n${lines.join('\n')}\n${indent(baseIndent)}}`;
}

function formatArray(arr: unknown[], baseIndent: number): string {
  if (arr.length === 0) return '[]';

  const inner = baseIndent + 2;
  const items = arr.map((item) => {
    const formatted = typeof item === 'object' && item !== null && !Array.isArray(item)
      ? formatObject(item as Record<string, unknown>, inner)
      : json(item);
    return `${indent(inner)}${formatted},`;
  });

  return `[\n${items.join('\n')}\n${indent(baseIndent)}]`;
}
