export const PRISM_DARK_THEME: Record<string, string> = {
  '--prism-primary': '#a78bfa',
  '--prism-primary-from': '#5f16ba',
  '--prism-primary-to': '#3052f2',
  '--prism-accent': '#e13990',
  '--prism-bg': '#0c0a14',
  '--prism-bg-surface': '#13101e',
  '--prism-bg-elevated': '#1c1830',
  '--prism-text': '#ede8f8',
  '--prism-text-muted': '#7b6e94',
  '--prism-border': 'rgba(255,255,255,0.07)',
  '--prism-sidebar-bg': '#0f0c1a',
  '--prism-sidebar-width': '280px',
  '--prism-header-height': '56px',
  '--prism-font-family': 'system-ui, -apple-system, sans-serif',
  '--prism-font-mono': 'ui-monospace, "Cascadia Code", monospace',
  '--prism-radius': '8px',
  '--prism-radius-sm': '4px',
  '--prism-panel-height': '240px',
  '--prism-glow': 'rgba(167,139,250,0.15)',
  '--prism-input-bg': 'rgba(255,255,255,0.04)',
};

export const PRISM_LIGHT_THEME: Record<string, string> = {
  '--prism-primary': '#5f16ba',
  '--prism-primary-from': '#5f16ba',
  '--prism-primary-to': '#3052f2',
  '--prism-accent': '#e13990',
  '--prism-bg': '#fbf9fe',
  '--prism-bg-surface': '#f3effe',
  '--prism-bg-elevated': '#ffffff',
  '--prism-text': '#1a0e2e',
  '--prism-text-muted': '#6b5e80',
  '--prism-border': 'rgba(95,22,186,0.10)',
  '--prism-sidebar-bg': '#eee6fd',
  '--prism-sidebar-width': '280px',
  '--prism-header-height': '56px',
  '--prism-font-family': 'system-ui, -apple-system, sans-serif',
  '--prism-font-mono': 'ui-monospace, "Cascadia Code", monospace',
  '--prism-radius': '8px',
  '--prism-radius-sm': '4px',
  '--prism-panel-height': '240px',
  '--prism-glow': 'rgba(95,22,186,0.10)',
  '--prism-input-bg': 'rgba(95,22,186,0.04)',
};

export const PRISM_DEFAULT_THEME = PRISM_DARK_THEME;
