import type { ScannedComponent } from '../../plugin/plugin.types.js';
import type { StyleguidePage } from '../../plugin/page.types.js';

export interface RuntimeManifestOptions {
  components: ScannedComponent[];
  libraryImportPath: string;
  pages?: StyleguidePage[];
}

export function generateRuntimeManifest(options: RuntimeManifestOptions): string {
  const { components, libraryImportPath, pages } = options;

  const classNames = components.map((c) => c.className);
  const lines: string[] = [
    '// AUTO-GENERATED by ng-prism — do not edit!',
    "import type { RuntimeManifest } from 'ng-prism/plugin';",
  ];

  if (classNames.length > 0) {
    lines.push(`import { ${classNames.join(', ')} } from '${libraryImportPath}';`);
  }

  lines.push('');
  lines.push('export const PRISM_RUNTIME_MANIFEST: RuntimeManifest = {');
  lines.push('  components: [');

  for (const comp of components) {
    lines.push('    {');
    lines.push(`      type: ${comp.className},`);
    lines.push(`      meta: ${formatMeta(comp, 6)},`);
    lines.push('    },');
  }

  lines.push('  ],');

  if (pages && pages.length > 0) {
    lines.push(`  pages: ${JSON.stringify(pages, null, 2).split('\n').map((l, i) => i === 0 ? l : '  ' + l).join('\n')},`);
  }

  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

function json(value: unknown): string {
  return JSON.stringify(value);
}

function indent(depth: number): string {
  return ' '.repeat(depth);
}

function formatMeta(comp: ScannedComponent, baseIndent: number): string {
  const inner = baseIndent + 2;
  const lines = [
    `${indent(inner)}className: ${json(comp.className)},`,
    `${indent(inner)}filePath: ${json(comp.filePath)},`,
    `${indent(inner)}showcaseConfig: ${formatObject(comp.showcaseConfig as unknown as Record<string, unknown>, inner)},`,
    `${indent(inner)}inputs: ${formatArray(comp.inputs, inner)},`,
    `${indent(inner)}outputs: ${formatArray(comp.outputs, inner)},`,
    `${indent(inner)}componentMeta: ${formatObject(comp.componentMeta, inner)},`,
  ];

  if (comp.meta && Object.keys(comp.meta).length > 0) {
    lines.push(`${indent(inner)}meta: ${formatObject(comp.meta as Record<string, unknown>, inner)},`);
  }

  return `{\n${lines.join('\n')}\n${indent(baseIndent)}}`;
}

function formatObject(obj: Record<string, unknown>, baseIndent: number): string {
  const entries = Object.entries(obj).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '{}';

  const inner = baseIndent + 2;
  const lines = entries.map(([key, value]) => {
    const formatted = Array.isArray(value)
      ? formatArray(value, inner)
      : typeof value === 'object' && value !== null
        ? formatObject(value as Record<string, unknown>, inner)
        : json(value);
    return `${indent(inner)}${key}: ${formatted},`;
  });

  return `{\n${lines.join('\n')}\n${indent(baseIndent)}}`;
}

function formatArray(arr: unknown[], baseIndent: number): string {
  if (arr.length === 0) return '[]';

  const inner = baseIndent + 2;
  const items = arr.map((item) => {
    const formatted = typeof item === 'object' && item !== null && !Array.isArray(item)
      ? formatObject(item as Record<string, unknown>, inner)
      : json(item);
    return `${indent(inner)}${formatted},`;
  });

  return `[\n${items.join('\n')}\n${indent(baseIndent)}]`;
}
