import type { ScannedComponent } from '../../plugin/plugin.types.js';
import { generateRuntimeManifest } from './runtime-manifest.generator.js';

const BUTTON: ScannedComponent = {
  className: 'ButtonComponent',
  filePath: 'src/lib/button/button.component.ts',
  showcaseConfig: {
    title: 'Button',
    category: 'Inputs',
    variants: [
      { name: 'Primary', inputs: { variant: 'primary', label: 'Click me' } },
    ],
  },
  inputs: [
    { name: 'variant', type: 'union', values: ['primary', 'secondary'], defaultValue: 'primary', required: false },
    { name: 'label', type: 'string', defaultValue: 'Button', required: false },
  ],
  outputs: [{ name: 'clicked', doc: 'Click event' }],
  componentMeta: { selector: 'my-button', standalone: true, isDirective: false },
};

const CARD: ScannedComponent = {
  className: 'CardComponent',
  filePath: 'src/lib/card/card.component.ts',
  showcaseConfig: { title: 'Card', category: 'Layout' },
  inputs: [{ name: 'title', type: 'string', defaultValue: '', required: false }],
  outputs: [],
  componentMeta: { selector: 'my-card', standalone: true, isDirective: false },
};

describe('generateRuntimeManifest', () => {
  it('should generate the type import from ng-prism/plugin', () => {
    const source = generateRuntimeManifest({ components: [BUTTON], libraryImportPath: 'my-lib' });

    expect(source).toContain("import type { RuntimeManifest } from 'ng-prism/plugin';");
  });

  it('should generate named imports from the library', () => {
    const source = generateRuntimeManifest({ components: [BUTTON, CARD], libraryImportPath: 'my-lib' });

    expect(source).toContain("import { ButtonComponent, CardComponent } from 'my-lib';");
  });

  it('should export PRISM_RUNTIME_MANIFEST with RuntimeManifest type', () => {
    const source = generateRuntimeManifest({ components: [BUTTON], libraryImportPath: 'my-lib' });

    expect(source).toContain('export const PRISM_RUNTIME_MANIFEST: RuntimeManifest');
  });

  it('should reference the component class as type (not a string)', () => {
    const source = generateRuntimeManifest({ components: [BUTTON], libraryImportPath: 'my-lib' });

    expect(source).toContain('type: ButtonComponent,');
    expect(source).not.toContain('type: "ButtonComponent"');
  });

  it('should serialize meta with className, filePath, inputs, outputs, componentMeta', () => {
    const source = generateRuntimeManifest({ components: [BUTTON], libraryImportPath: 'my-lib' });

    expect(source).toContain('className: "ButtonComponent"');
    expect(source).toContain('filePath: "src/lib/button/button.component.ts"');
    expect(source).toContain('selector: "my-button"');
    expect(source).toContain('name: "variant"');
    expect(source).toContain('name: "clicked"');
  });

  it('should handle empty components array', () => {
    const source = generateRuntimeManifest({ components: [], libraryImportPath: 'my-lib' });

    expect(source).toContain('components: [');
    expect(source).not.toContain('type:');
    expect(source).not.toContain("import {");
  });

  it('should include the auto-generated comment', () => {
    const source = generateRuntimeManifest({ components: [], libraryImportPath: 'my-lib' });

    expect(source).toContain('// AUTO-GENERATED by ng-prism');
  });

  it('should use the provided libraryImportPath for the import', () => {
    const source = generateRuntimeManifest({ components: [BUTTON], libraryImportPath: '@my-org/components' });

    expect(source).toContain("from '@my-org/components'");
  });

  it('should generate grouped imports when components have different importPaths', () => {
    const pill: ScannedComponent = {
      ...BUTTON,
      className: 'PillComponent',
      importPath: 'sgui-lib/atoms/pill',
    };
    const tooltip: ScannedComponent = {
      ...CARD,
      className: 'TooltipComponent',
      importPath: 'sgui-lib/overlay/tooltip',
    };

    const source = generateRuntimeManifest({ components: [pill, tooltip], libraryImportPath: 'sgui-lib' });

    expect(source).toContain("import { PillComponent } from 'sgui-lib/atoms/pill';");
    expect(source).toContain("import { TooltipComponent } from 'sgui-lib/overlay/tooltip';");
    expect(source).not.toContain("from 'sgui-lib';");
  });

  it('should group multiple components from the same importPath', () => {
    const pill: ScannedComponent = {
      ...BUTTON,
      className: 'PillComponent',
      importPath: 'sgui-lib/atoms/pill',
    };
    const pillModel: ScannedComponent = {
      ...CARD,
      className: 'PillModelComponent',
      importPath: 'sgui-lib/atoms/pill',
    };

    const source = generateRuntimeManifest({ components: [pill, pillModel], libraryImportPath: 'sgui-lib' });

    expect(source).toContain("import { PillComponent, PillModelComponent } from 'sgui-lib/atoms/pill';");
  });

  it('should fall back to libraryImportPath when component has no importPath', () => {
    const withPath: ScannedComponent = { ...BUTTON, className: 'PillComponent', importPath: 'sgui-lib/atoms/pill' };
    const withoutPath: ScannedComponent = { ...CARD };

    const source = generateRuntimeManifest({ components: [withPath, withoutPath], libraryImportPath: 'sgui-lib' });

    expect(source).toContain("import { PillComponent } from 'sgui-lib/atoms/pill';");
    expect(source).toContain("import { CardComponent } from 'sgui-lib';");
  });
});
